### ISSUE TITLE
find a better way to geocode addresses

### ISSUE THREAD

**Issue by mrcnc** [codefornola/assessor-scraper#3]
Currently geocoding is done using the Mapzen API, which is [rate limited](https://mapzen.com/documentation/overview/rate-limits/) at 25,000 geocoding requests per month.  Since we're dealing with ~160,000 properties, we'll need to find another solution to geocode all the addresses.

One option is to setup a [pelias server](https://github.com/pelias/pelias), which is the same thing Mapzen uses anyway.

**Comment by bhelx** [comment]
In my scraper I took the centroid of the bounding box provided in the url to the parcel viewer. This is in the "Show Parcel Map" button on every listing. Example: http://qpublic9.qpublic.net/la_orleans_display.php?KEY=2336-OCTAVIAST has a url to parcel viewer:

```
http://qpublic9.qpublic.net/qpmap4/map.php?county=la_orleans&parcel=41050873&extent=3667340+524208+3667804+524540&layers=parcels+aerials+roads+lakes
```

1. Parse the `extent` param (bounding box)
2. Take the centroid of the bounding box
3. Convert to wgs84

I believe it's faster and more accurate than trying to geocode.

**Comment by mrcnc** [comment]
Thanks for the suggestion!  I still think having a local geocoder would be useful for other applications in the future.  Also, maybe we can do a comparison to see if the (Geonames)[http://www.geonames.org/] dataset lines up with what we calculate from the extent.
