### ISSUE TITLE
parcel_ids.txt missing

### ISSUE THREAD

**Issue by maxgaudin** [codefornola/assessor-scraper#5]
So I googling how to scrape data from the assessor's site, but not even New Orleans. And I found this repo which is fantastic :)

When I run: scrapy shell http://qpublic9.qpublic.net/la_orleans_display.php?KEY=2336-OCTAVIAST

I get: FileNotFoundError: [Errno 2] No such file or directory: 'parcel_ids.txt'

What is parcel_ids.txt and why isn't it there?

**Comment by nihonjinrxs** [comment]
Looks like that file is created by running the [`parcel_id_extractor.py` script](https://github.com/codefornola/assessor-scraper/blob/master/parcel_id_extractor.py).  Maybe try running that first?
